In [1]:
#!pip install --upgrade tensorflow

In [19]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [20]:
from keras.datasets import mnist
from keras import models
from keras import layers
from keras.utils import to_categorical

In [21]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(f"Train image shape: {train_images.shape}")
print(f"Train labels length: {len(train_labels)}")
print(f"Train labels: {train_labels}")

print(f"Test image shape: {test_images.shape}")
print(f"Test labels length: {len(test_labels)}")
print(f"Test labels: {test_labels}")

Train image shape: (60000, 28, 28)
Train labels length: 60000
Train labels: [5 0 4 ... 5 6 8]
Test image shape: (10000, 28, 28)
Test labels length: 10000
Test labels: [7 2 1 ... 4 5 6]


In [22]:
net = models.Sequential()
net.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
net.add(layers.Dense(10, activation='softmax'))

In [23]:
net.compile(optimizer='rmsprop',
            loss='categorical_crossentropy',
            metrics=['accuracy'])

In [24]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

In [25]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
print(f"Categorical train labels: {train_labels}")
print(f"Categorical test labels: {test_labels}")

Categorical train labels: [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Categorical test labels: [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [26]:
net.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 3s 46us/step - loss: 0.2608 - acc: 0.9246
Epoch 2/5
60000/60000 [==============================] - 2s 41us/step - loss: 0.1041 - acc: 0.9692
Epoch 3/5
60000/60000 [==============================] - 2s 39us/step - loss: 0.0680 - acc: 0.9795
Epoch 4/5
60000/60000 [==============================] - 3s 43us/step - loss: 0.0491 - acc: 0.9853
Epoch 5/5
60000/60000 [==============================] - 3s 43us/step - loss: 0.0378 - acc: 0.9885
